# Sandbox config example

# global parameters
project_name: 'demo-bench'
experiment_name: 'single_op_language_score'              # for wandb tracer name
work_dir: './outputs/demo-bench'                         # the default output dir for meta logging

# configs for each job, the jobs will be executed according to the order in the list
probe_job_configs:

refine_recipe_job_configs:

execution_job_configs:
  - hook: 'GeneralDataExecutorHook'
    meta_name: 'convert_to_ea_fmt'
    extra_configs:
      type: 'dj_to_easyanimate_video_dataset_conversion'
      dataset_path: './outputs/demo-bench/demo-dataset-with-multi-op-stats.json'
      export_path: './outputs/demo-bench/'
  # train model
  - hook: 'TrainModelHook'
    meta_name:
    dj_configs:
    extra_configs: './configs/data_juicer_recipes/sandbox/easyanimate_text_to_video/model_train_2_epoch.yaml' # the input data is set to be demo-dataset-with-multi-op-stats.jsonl
  # infer model
  - hook: 'InferModelHook'
    local:
      extra_configs.train.model_path.lora_path: "../../../outputs/demo-bench/models/checkpoint-2.safetensors"
    meta_name:
    dj_configs:
    extra_configs: './configs/data_juicer_recipes/sandbox/easyanimate_text_to_video/model_infer.yaml'

evaluation_job_configs:
  # vbench evaluation
  - hook: 'EvaluateDataHook'
    meta_name: 'vbench_eval'
    dj_configs:
    extra_configs: './configs/data_juicer_recipes/sandbox/easyanimate_text_to_video/vbench_eval.yaml'
