# You need to replace all "<internvl_home>" in the config files with your own real path to InternVL home on you machine.

project_name: 'all_text_image_stats'
dataset_path: '<internvl_home>/internvl_chat/data/coco/coco_karpathy_train_567k_dj_fmt.jsonl'
np: 16

export_path: '<internvl_home>/internvl_chat/data/coco/computed_stats/data_with_stats.jsonl'

keep_stats_in_res_ds: true
export_original_dataset: true

# process schedule
process:
  - alphanumeric_filter:
  - character_repetition_filter:
  - flagged_words_filter:
      lang: en
  - image_aspect_ratio_filter:
  - image_shape_filter:
  - image_size_filter:
  - language_id_score_filter:
      lang: en
  - perplexity_filter:
      lang: en
  - special_characters_filter:
  - stopwords_filter:
      lang: en
  - text_length_filter:
  - token_num_filter:
      hf_tokenizer: EleutherAI/pythia-6.9b-deduped
  - words_num_filter:
      lang: en
  - word_repetition_filter:
      lang: en
  - text_action_filter:
      lang: en
  - text_entity_dependency_filter:
      lang: en
  - image_aesthetics_filter:
      hf_scorer_model: shunk031/aesthetics-predictor-v2-sac-logos-ava1-l14-linearMSE
  - image_nsfw_filter:
      hf_nsfw_model: Falconsai/nsfw_image_detection
  - image_text_matching_filter:
      hf_blip: Salesforce/blip-itm-base-coco
  - image_text_similarity_filter:
      hf_clip: openai/clip-vit-base-patch32
  - image_watermark_filter:
      hf_watermark_model: amrul-hzz/watermark_detector
  - phrase_grounding_recall_filter:
      hf_owlvit: google/owlvit-base-patch32
