# This is the main config file for reproducing the Sandbox experiments for InternVL COCO Caption task.
#
# You can follow the doc [here](https://internvl.readthedocs.io/en/latest/get_started/installation.html) to install
# the InternVL before starting it, or you can only need to clone and let the sandbox create and install the environment
# automatically.
# Then you need to prepare the model and dataset following this doc [here](https://internvl.readthedocs.io/en/latest/tutorials/coco_caption_finetune.html#).
# And you need to replace all "<internvl_home>" in the config files with your own real path to InternVL home on you machine.

# global parameters
project_name: 'sandbox-internvl-coco-caption'
experiment_name: 'sandbox-internvl'               # for wandb tracer name
work_dir: './outputs/sandbox-internvl'            # the default output dir for meta logging
resume: true                                      # allow resume from the existing context infos

pipelines:
  # Baseline Preparation:
  # 1. convert the coco caption
  # 2. downsample the whole dataset randomly to form a baseline data pool with only 1/3 size of the original one
  - baseline_preparation:
      execution_job_configs:
        - hook: 'GeneralDataExecutorHook'
          meta_name: 'convert_to_coco_caption'
          output: 'output_paths'
          extra_configs:
            type: 'coco_caption_to_dj_conversion'
            dataset_path: '<internvl_home>/internvl_chat/data/coco/annotations/coco_karpathy_train_567k.jsonl'
            export_path: '<internvl_home>/internvl_chat/data/coco/'
        - hook: 'GeneralDataExecutorHook'
          meta_name: 'generate_meta_file_dj_fmt'
          input:
            extra_configs.dataset_path: '-1.output_paths'
          output: 'output_paths'
          extra_configs:
            type: 'coco_caption_meta_generation'
            export_path: '<internvl_home>/internvl_chat/data/coco/'
            data_root_path: '<internvl_home>/internvl_chat'

  # Single-OP Exps:
  # 3. analyze the data for all image & text stats
  # 4. prepare data pools according to the analyzed data, and add the baseline data pool
  # 5. prepare the meta files for these single-op data pools in step 4
  # 6. start the training for single-op data pools
  # 7. start the evaluation for models trained on single-op data pools
  - single_op_exps:
      probe_job_configs:
        - hook: 'ProbeViaAnalyzerHook'
          meta_name: 'analysis_all_stats'
          input:
            dj_configs.dataset_path: 'baseline_preparation.convert_to_coco_caption.output_paths'
          output: 'dataset_with_stats_paths'
          dj_configs: 'configs/data_juicer_recipes/sandbox/internvl_coco_caption/all_text_image_stats.yaml'
      execution_job_configs:
        - hook: 'DataPoolManipulationHook'
          meta_name: 'construct_single_op_data_pools'
          input:
            extra_configs.dataset_path: '-1.dataset_with_stats_paths'
          output: 'single_op_data_pool_paths'
          extra_configs:
            type: 'data_pool_construction'
            dataset_path: '<updated_by_the_input_mapping>'
            export_path: '<internvl_home>/internvl_chat/data/coco/single_ops/'
            split_ratios: ['1/3', '2/3']
        - hook: 'GeneralDataExecutorHook'
          input:
            extra_configs.dataset_path: '-1.single_op_data_pool_paths'
          output: 'single_op_data_pool_meta_paths'
          extra_configs:
            type: 'coco_caption_meta_generation'
            dataset_path: '<internvl_home>/internvl_chat/data/coco/single_ops/<stats_key_name>/<parts>.jsonl'
            export_path: '<internvl_home>/internvl_chat/data/coco/single_ops/metas/'
            data_root_path: '<internvl_home>/internvl_chat/'
        - hook: 'TrainModelHook'
          meta_name: 'single_op_exps_train'
          input:
            extra_configs.meta_paths: '-1.single_op_data_pool_meta_paths'
          output: 'single_op_exps_trained_model_paths'
          extra_configs: 'configs/data_juicer_recipes/sandbox/internvl_coco_caption/internvl_train_config.yaml'
      evaluation_job_configs:
        - hook: 'EvaluateModelHook'
          meta_name: 'single_op_exps_eval'
          input:
            extra_configs.ckpt_paths: '-1.single_op_exps_trained_model_paths'
          output: 'single_op_exps_eval_results'
          extra_configs: 'configs/data_juicer_recipes/sandbox/internvl_coco_caption/internvl_eval_config.yaml'

  # Multiple-OP Exps:
  # 8. rank data pools according to the evaluation results, the rank method is specified to the relative improvements
  #   to the model trained on baseline data pool
  # 9. combine the top data pools to several combined data pools
  # 10. downsampling the data pools to align with the one with the least samples, including the baseline data pool
  # 11. prepare meta files for the combined and downsampled data pools in step 10
  # 12. start the training for multiple-op data pools
  # 13. start the evaluation for models trained on multiple-op data pools
  - multiple_op_exps:
      probe_job_configs:
        - hook: 'GeneralProbeHook'
          meta_name: 'rank_single_op_data_pools'
          input:
            extra_configs.dataset_path: 'single_op_exps.construct_single_op_data_pools.single_op_data_pool_paths'
            extra_configs.metrics: '-1.single_op_exps_eval_results'
          output: 'top3_single_op_data_pool_paths'
          extra_configs:
            type: 'data_pool_ranking'
            dataset_path: '<internvl_home>/internvl_chat/data/coco/single_ops/<stats_key_name>/<parts>.jsonl'
            metrics: '<require_results_from_the_previous_hook>'
            ranking_keys:
              - 'avg_score'
            descending: true
            top_n: 3
      execution_job_configs:
        - hook: 'DataPoolManipulationHook'
          input:
            extra_configs.dataset_path: '-1.top3_single_op_data_pool_paths'
          output: 'top3_combined_data_pool_paths'
          extra_configs:
            type: 'data_pool_combination'
            dataset_path: '<internvl_home>/internvl_chat/data/coco/single_ops/<stats_key_name>/<top_n_parts>.jsonl'
            export_path: '<internvl_home>/internvl_chat/data/coco/multiple_ops/'
        - hook: 'DataPoolManipulationHook'
          meta_name: 'align_data_pool_size'
          input:
            extra_configs.dataset_path: '-1.top3_combined_data_pool_paths'
          output: 'top3_aligned_combined_data_pool_paths'
          extra_configs:
            type: 'data_pool_downsampling'
            dataset_path: '<internvl_home>/internvl_chat/data/coco/multiple_ops/<combined_data_pools>.jsonl'
            export_path: '<internvl_home>/internvl_chat/data/coco/multiple_ops/'
            seed: 42
        - hook: 'GeneralDataExecutorHook'
          input:
            extra_configs.dataset_path: '-1.top3_aligned_combined_data_pool_paths'
          output: 'top3_aligned_combined_data_pool_meta_paths'
          extra_configs:
            type: 'coco_caption_meta_generation'
            dataset_path:
              - '<internvl_home>/internvl_chat/data/coco/multiple_ops/<downsampled_combined_data_pools>.jsonl'
            export_path: '<internvl_home>/internvl_chat/data/coco/multiple_ops/'
            data_root_path: '<internvl_home>/internvl_chat/'
        - hook: 'TrainModelHook'
          meta_name: 'multiple_op_exps_train'
          input:
            extra_configs.meta_paths: '-1.top3_aligned_combined_data_pool_meta_paths'
          output: 'multiple_op_exps_trained_model_paths'
          extra_configs: 'configs/data_juicer_recipes/sandbox/internvl_coco_caption/internvl_train_config.yaml'
      evaluation_job_configs:
        - hook: 'EvaluateModelHook'
          meta_name: 'multiple_op_exps_eval'
          input:
            extra_configs.ckpt_paths: '-1.multiple_op_exps_trained_model_paths'
          output: 'multiple_op_exps_eval_results'
          extra_configs: 'configs/data_juicer_recipes/sandbox/internvl_coco_caption/internvl_eval_config.yaml'

  # Scaling Exps:
  # 14. rank data pools according to the evaluation results, the rank method is specified to the relative improvements
  #   to the model trained on the aligned baseline data pool
  # 15. start the training for top-3 multiple-op data pools on larger scales (2B, 4B, 26B)
  # 16. start the evaluation for models trained on top-3 multiple-op data pools on larger scales
  - scaling_exps:
      probe_job_configs:
        - hook: 'GeneralProbeHook'
          meta_name: 'rank_multiple_op_data_pools'
          input:
            extra_configs.dataset_path: 'multiple_op_exps.align_data_pool_size.top3_aligned_combined_data_pool_paths'
            extra_configs.metrics: '-1.multiple_op_exps_eval_results'
          output: 'top3_multiple_op_data_pool_paths'
          extra_configs:
            type: 'data_pool_ranking'
            dataset_path: '<internvl_home>/internvl_chat/data/coco/multiple_ops/<downsampled_combined_data_pools>.jsonl'
            metrics: '<require_results_from_the_previous_hook>'
            ranking_keys:
              - 'avg_score'
            descending: true
            top_n: 3
      execution_job_configs:
        - hook: 'GeneralDataExecutorHook'
          meta_name: 'generate_meta_files_for_scaling_exps'
          input:
            extra_configs.dataset_path: '-1.top3_multiple_op_data_pool_paths'
          output: 'top3_multiple_op_data_pool_meta_paths'
          extra_configs:
            type: 'coco_caption_meta_generation'
            dataset_path:
              - '<internvl_home>/internvl_chat/data/coco/multiple_ops/<top_n_downsampled_combined_data_pools>.jsonl'
            export_path: '<internvl_home>/internvl_chat/data/coco/multiple_ops/'
            data_root_path: '<internvl_home>/internvl_chat/'
        - hook: 'TrainModelHook'
          meta_name: 'scaling_op_exps_train_2B'
          input:
            extra_configs.meta_paths: 'scaling_exps.generate_meta_files_for_scaling_exps.top3_multiple_op_data_pool_meta_paths'
          output: 'scaling_op_exps_2B_trained_model_paths'
          local:
            extra_configs.model_name_or_path: '<internvl_home>/internvl_chat/pretrained/InternVL2-2B'
            extra_configs.conv_style_or_scale: '2B'
          extra_configs: 'configs/data_juicer_recipes/sandbox/internvl_coco_caption/internvl_train_config.yaml'
        - hook: 'TrainModelHook'
          meta_name: 'scaling_op_exps_train_4B'
          input:
            extra_configs.meta_paths: 'scaling_exps.generate_meta_files_for_scaling_exps.top3_multiple_op_data_pool_meta_paths'
          output: 'scaling_op_exps_4B_trained_model_paths'
          local:
            extra_configs.model_name_or_path: '<internvl_home>/internvl_chat/pretrained/InternVL2-4B'
            extra_configs.conv_style_or_scale: '4B'
          extra_configs: 'configs/data_juicer_recipes/sandbox/internvl_coco_caption/internvl_train_config.yaml'
        - hook: 'TrainModelHook'
          meta_name: 'scaling_op_exps_train_26B'
          input:
            extra_configs.meta_paths: 'scaling_exps.generate_meta_files_for_scaling_exps.top3_multiple_op_data_pool_meta_paths'
          output: 'scaling_op_exps_26B_trained_model_paths'
          local:
            extra_configs.model_name_or_path: '<internvl_home>/internvl_chat/pretrained/InternVL2-26B'
            extra_configs.conv_style_or_scale: '26B'
          extra_configs: 'configs/data_juicer_recipes/sandbox/internvl_coco_caption/internvl_train_config.yaml'
      evaluation_job_configs:
        - hook: 'EvaluateModelHook'
          meta_name: 'scaling_op_exps_eval_2B'
          input:
            extra_configs.ckpt_paths: 'scaling_exps.scaling_op_exps_train_2B.scaling_op_exps_2B_trained_model_paths'
          extra_configs: 'configs/data_juicer_recipes/sandbox/internvl_coco_caption/internvl_eval_config.yaml'
        - hook: 'EvaluateModelHook'
          meta_name: 'scaling_op_exps_eval_4B'
          input:
            extra_configs.ckpt_paths: 'scaling_exps.scaling_op_exps_train_4B.scaling_op_exps_4B_trained_model_paths'
          extra_configs: 'configs/data_juicer_recipes/sandbox/internvl_coco_caption/internvl_eval_config.yaml'
        - hook: 'EvaluateModelHook'
          meta_name: 'scaling_op_exps_eval_26B'
          input:
            extra_configs.ckpt_paths: 'scaling_exps.scaling_op_exps_train_26B.scaling_op_exps_26B_trained_model_paths'
          extra_configs: 'configs/data_juicer_recipes/sandbox/internvl_coco_caption/internvl_eval_config.yaml'
