# Sandbox config example

# global parameters
project_name: 'demo-bench'
experiment_name: 'single_op_language_score'              # for wandb tracer name
work_dir: './outputs/demo-bench'                         # the default output dir for meta logging

# configs for each job, the jobs will be executed according to the order in the list
probe_job_configs:

refine_recipe_job_configs:

execution_job_configs:
  # train model
  - hook: 'TrainModelHook'
    meta_name:
    dj_configs:
    extra_configs: './configs/demo/bench/model_train_2_epoch.yaml' # the input data is set to be demo-dataset-with-multi-op-stats.jsonl
  # infer model
  - hook: 'InferModelHook'
    meta_name:
    dj_configs:
    extra_configs: './configs/demo/bench/model_infer.yaml'

evaluation_job_configs:
  # vbench evaluation
  - hook: 'EvaluateDataHook'
    meta_name: 'vbench_eval'
    dj_configs:
    extra_configs: './configs/demo/bench/vbench_eval.yaml'
