type: vbench_video_evaluator

# The vbench prompts for video generation. Use VBench_full_info.json for full eval.
prompt_path: ./tools/mm_eval/vbench_metrics/VBench_mini_info.json

# The path to the dir of generated videos
videos_path: ./outputs/demo-bench/generated_videos

# The dir to store the eval results
result_dir: ./outputs/demo-bench/eval_results

# Give a name for this eval
eval_name: mini_test

# If true, load the required model for VBench from the cache path of environment parameter VBENCH_CACHE_DIR
load_ckpt_from_local: false

# The dimensions considered in this eval.
# All dimensions include: ['subject_consistency', 'background_consistency', 'temporal_flickering',
# 'motion_smoothness', 'dynamic_degree', 'aesthetic_quality', 'imaging_quality', 'object_class',
# 'multiple_objects', 'human_action', 'color', 'spatial_relationship', 'scene', 'temporal_style',
# 'appearance_style', 'overall_consistency']
dimension_list:
  - subject_consistency
  - dynamic_degree
