# You need to replace dataset_path and export_path in the config files with your own real path to the dataset home and path on you machine.

project_name: 'prompt_generating'
np: 8

dataset_path: 'demos/data/auto-prompt-optim/demo-dataset-prompts.jsonl'

export_path: './outputs/auto-prompt-optimization-for-grader-model/generated_prompts/new_prompts.jsonl'

export_original_dataset: true

text_keys: "prompt"

use_cache: false

process:
  - optimize_prompt_mapper:
      api_or_hf_model: 'qwen2.5-32b-instruct'
      prompt_key: 'prompt'
      gen_num: 3
      max_example_num: 3
