# global parameters
project_name: 'Data-Juicer-recipes-T2V-evolution'
dataset_path: '/path/to/your/dataset'  # path to your dataset directory or file
export_path: '/path/to/your/dataset.jsonl'

np: 4  # number of subprocess to process your dataset

# process schedule
# a list of several process operators with their arguments
process:
  - video_nsfw_filter:
      hf_nsfw_model: Falconsai/nsfw_image_detection
      score_threshold: 0.000195383
      frame_sampling_method: uniform
      frame_num: 3
      reduce_mode: avg
      any_or_all: any
      mem_required: '1GB'
  - video_frames_text_similarity_filter:
      hf_clip: openai/clip-vit-base-patch32
      min_score: 0.306337
      max_score: 1.0
      frame_sampling_method: uniform
      frame_num: 3
      horizontal_flip: false
      vertical_flip: false
      reduce_mode: avg
      any_or_all: any
      mem_required: '10GB'
  - video_motion_score_filter:
      min_score: 3
      max_score: 20
      sampling_fps: 2
      any_or_all: any
  - video_aesthetics_filter:
      hf_scorer_model: shunk031/aesthetics-predictor-v2-sac-logos-ava1-l14-linearMSE
      min_score: 0.418164
      max_score: 1.0
      frame_sampling_method: 'uniform'
      frame_num: 3
      reduce_mode: avg
      any_or_all: any
      mem_required: '1500MB'
  - video_duration_filter:
      min_duration: 2
      max_duration: 100000
      any_or_all: any
