# Data-Juicer recipe implementation for "Img-Diff: Contrastive Data Synthesis for Multimodal Large Language Models" (CVPR2025)
# global parameters

project_name: 'Img-Diff-recipe'
dataset_path: '/path/to/your/dataset'  # path to your dataset directory or file
export_path: '/path/to/your/dataset.jsonl'

text_keys: caption1


np: 1  # number of subprocess to process your dataset
open_tracer: true

# process schedule
process:
  - sentence_augmentation_mapper:
      hf_model: Qwen/Qwen2-7B-Instruct
      task_sentence: "Please replace one entity in this sentence with another entity, such as an animal, a vehicle, a piece of furniture or other physically consistent object. Ensure the replaced sentence adheres to physical plausibility. Please only answer with the replaced sentence."
      max_new_tokens: 512
      temperature: 0.9
      top_p: 0.95
      num_beams: 1
      text_key: caption1
      text_key_second: caption2

  - sdxl_prompt2prompt_mapper:
      hf_diffusion: stabilityai/stable-diffusion-xl-base-1.0
      torch_dtype: fp16
      text_key: caption1
      text_key_second: caption2

  - imgdiff_difference_area_generator_mapper:
      image_pair_similarity_filter_args:
        min_score_1: 0.9
        max_score_1: 0.99
        min_score_2: 0
        max_score_2: 0.85
        hf_clip: openai/clip-vit-base-patch32
        num_proc: 1
      image_segment_mapper_args:
        imgsz: 1024
        conf: 0.05
        iou: 0.5
        model_path: FastSAM-x.pt
      image_text_matching_filter_args:
        min_score: 0.4
        max_score: 1.0
        hf_blip: Salesforce/blip-itm-base-coco
        num_proc: 1

  - imgdiff_difference_caption_generator_mapper:
      mllm_mapper_args:
        max_new_tokens: 1024
        temperature: 0.2
        num_beams: 1
        hf_model: llava-hf/llava-v1.6-vicuna-7b-hf
      image_text_matching_filter_args:
        min_score: 0.4
        max_score: 1.0
        hf_blip: Salesforce/blip-itm-base-coco
        num_proc: 1
      text_pair_similarity_filter_args:
        min_score: 0
        max_score: 0.8
        hf_clip: openai/clip-vit-base-patch32
        text_key_second: target_text
        num_proc: 1
