type: video_inception_evaluator

# The path to generated dataset. Only support for `jsonl` format. The video paths are put in the list under `videos` keys.
fake_data_path: /path/to/the/generated/dj_format_dataset
# The path to ground truth dataset. Only support for `jsonl` format. The video paths are put in the list under `videos` keys. Required when computing FVD, FID, KID, and PR.
real_data_path: /path/to/the/groundtruth/dj_format_dataset
# The root directory to store the generated videos. If it is not none, the paths in jsonl file at fake_data_path are relative paths on it, else are absolute path.
fake_mm_dir: null
# The root directory to store the real videos. If it is not none, the paths in jsonl file at real_data_path are relative paths on it, else are absolute path.
real_mm_dir: null
# Path to the corresponding detection model. Download the model from web if it is None.
detector_path: null
# Path to JSON filename for saving results.
result_path: ./outputs/demo-sandbox/inception_eval_results.jsonl

# How many runs of the metric to average over.
num_runs: 1
# Sampled frames will be resized to this height and width.
height: 240
width: 320
# Whether to replace the dataset stats cache.
replace_cache: false
# Whether to log progress.
verbose: false

seed: 42

# The name of metric applied, currently support `fvd2048_16f`, `fvd2048_128f`, `fvd2048_128f_subsample8f`, `kvd2048_16f`, `isv2048_ucf`, `prv2048_3n_16f`, `fid50k`, `kid50k`, `is50k`, `pr50k_3n`.
#     - `fvd2048_16f`: Compute Frechet Video Distance (FVD), sample 2048 times in dataset, 16 adjacent frames each time.
#     - `fvd2048_128f`: Compute Frechet Video Distance (FVD), sample 2048 times in dataset, 128 adjacent frames each time.
#     - `fvd2048_128f_subsample8f`: Compute Frechet Video Distance (FVD), sample 2048 times in dataset, 16 frames each time, sample 1 frame every adjacent 8 frames.
#     - `kvd2048_16f`: Compute Kernel Video Distance (KVD), sample 2048 times in dataset, 16 adjacent frames each time, split features to 100 subset to compute KVDs and return the mean.
#     - `isv2048_ucf`: Compute Inception Score of Videos (ISV), sample 2048 times in dataset, 16 frames each time, split features to 10 subset to compute ISs and return the mean and std.
#     - `prv2048_3n_16f`: Compute Precision/Recall of Videos (PRV), sample 2048 times in dataset, 16 adjacent frames each time, with the 4th nearest features to estimate the distributions.
#     - `fid50k`: Compute Frechet Inception Distance (FID) of frames, sample 50000 frames from fake dataset at most.
#     - `kid50k`: Compute Kernel Inception Distance (KID) of frames, sample 50000 frames from fake dataset at most, split features to 100 subset to compute KIDs and return the mean.
#     - `is50k`: Compute Inception Score(IS) of frames, sample 50000 frames from fake dataset at most, split features to 10 subset to compute ISs and return the mean and std.
#     - `pr50k_3n`: Compute Precision/Recall (PR) of frames, sample 50000 frames from fake dataset at most, with the 4th nearest features to estimate the distributions
metric: "fvd2048_16f"
