# Sandbox config example

# global parameters
project_name: 'demo-sandbox'
experiment_name: 'demo-sandbox-run0'              # for wandb tracer name
work_dir: './outputs/demo-sandbox'                # the default output dir for meta logging
hpo_config: null                                  # path to a configuration file when using auto-HPO tool.

# configs for each job, the jobs will be executed according to the order in the list
probe_job_configs:
  - hook: 'ProbeViaAnalyzerHook'
    meta_name: 'analysis_ori_data'
    dj_configs: 'configs/demo/process.yaml'
    extra_configs:
  # - hook: 'ProbeViaModelInferHook'
  #   meta_name: 'analysis_ori_model'
  #   dj_configs:
  #     dataset_path: './demos/data/demo-dataset.jsonl'
  #     export_path: './outputs/demo-sandbox/demo-sandbox.jsonl'
  #     data_probe_algo: 'uniform'
  #     data_probe_ratio: 0.5
  #     extra_configs:
  #       (...model configs)

refine_recipe_job_configs:
  - hook: 'RefineRecipeViaKSigmaHook'
    meta_name: 'analysis_ori_data'
    output: 'refined_recipe_path'
    dj_configs: 'configs/demo/process.yaml'
    extra_configs:
      path_k_sigma_recipe: './outputs/demo-process/k_sigma_new_recipe.yaml'
  # - hook: 'RefineRecipeViaModelFeedbackHook'
  #   meta_name:
  #   dj_configs:
  #   extra_configs:
  #     (...model configs)

execution_job_configs:
  - hook: 'ProcessDataHook'
    meta_name: 'process_data_with_refined_recipe'
    input:
      dj_configs: '-1.refined_recipe_path'
    output: 'processed_dataset_path'
    dj_configs: '<auto_replaced_with_previous_output>'
    extra_configs:
  - hook: 'TrainModelHook'
    meta_name: 'train_model'
    input:
      extra_configs.train_dataset: '-1.processed_dataset_path'
    dj_configs:
    extra_configs: 'configs/demo/sandbox/gpt3_extra_train_config.json'

evaluation_job_configs:
  - hook: 'ProbeViaAnalyzerHook'
    meta_name: 'analysis_processed_data'
    input:
      dj_configs.dataset_path: 'anonymous.process_data_with_refined_recipe.processed_dataset_path'
    dj_configs: 'configs/demo/process.yaml'
    extra_configs:
  # - hook: 'ProbeViaModelInferHook'
  #   meta_name: 'analysis_trained_model'
  #   dj_configs:
  #     dataset_path: './demos/data/demo-dataset.jsonl'
  #     export_path: './outputs/demo-sandbox/demo-sandbox.jsonl'
  #     data_probe_algo: 'uniform'
  #     data_probe_ratio: 0.5
  #     extra_configs:
  #       (...model configs)
  - hook: 'EvaluateDataHook'
    meta_name: 'eval_data'
    input:
      extra_configs.dataset_path: 'anonymous.process_data_with_refined_recipe.processed_dataset_path'
    dj_configs:
    extra_configs: 'configs/demo/sandbox/gpt3_data_quality_eval_config.yaml'
  # - hook: 'EvaluateModelHook'
  #   meta_name: 'eval_model'
  #   dj_configs:
  #   oextra_configs:
  #     (...model configs)
