# configs/demo/annotation.yaml
# Process config for human preference annotation with Label Studio

# Global parameters
project_name: 'demo-annotation-human-preference'
dataset_path: './demos/data/demo-dataset-annotation-human-preference.jsonl'
np: 1  # Use single process for annotation tasks
open_tracer: true

export_path: './outputs/demo-annotation-human-preference/annotated-data.jsonl'

# use prompt as the text field, which will be used in the label studio template
text_keys: "prompt"

# Process schedule
process:
  # Annotation step using Label Studio with human preference
  - human_preference_annotation_mapper:
      # general annotation project settings
      project_name_prefix: "Human_Preference_Annotation"
      wait_for_annotations: true  # Whether to wait for annotations to complete
      timeout: 3600  # Maximum time to wait for annotations in seconds (1 hour)
      poll_interval: 10  # Time between annotation status checks in seconds
      max_tasks_per_batch: 10  # Maximum number of tasks in a single batch
      notification_config:
        enabled: false

      # label studio connection settings
      api_url: "http://localhost:7070"  # Default Label Studio URL
      api_key: "05409236-67a5-4169-af96-a52a818d0e81"  # Your API key for label studio authentication # pragma: allowlist secret

      # human preference annotation settings
      prompt_key: "prompt"  # Prompt field
      answer1_key: "answer1"  # First answer option
      answer2_key: "answer2"  # Second answer option
      chosen_key: "chosen"  # Chosen field
      rejected_key: "rejected"  # Rejected field
