# configs/examples/annotation_with_notifications.yaml
# Process config for human preference annotation with Label Studio
# including email notifications for annotation events

# Global parameters
project_name: 'demo-annotation-human-preference'
dataset_path: './demos/data/demo-dataset-annotation-human-preference.jsonl'
np: 1  # Use single process for annotation tasks
open_tracer: true

export_path: './outputs/demo-annotation-human-preference/annotated-data.jsonl'

# use prompt as the text field, which will be used in the label studio template
text_keys: "prompt"

# Process schedule
process:
  # Annotation step using Label Studio with human preference
  - human_preference_annotation_mapper:
      # general annotation project settings
      project_name_prefix: "Human_Preference_Annotation"
      wait_for_annotations: true  # Whether to wait for annotations to complete
      timeout: 3600  # Maximum time to wait for annotations in seconds (1 hour)
      poll_interval: 10  # Time between annotation status checks in seconds
      max_tasks_per_batch: 10  # Maximum number of tasks in a single batch

      # label studio connection settings
      api_url: "http://localhost:7070"  # Default Label Studio URL
      api_key: "05409236-67a5-4169-af96-a52a818d0e81"  # Your API key for label studio authentication # pragma: allowlist secret

      # human preference annotation settings
      prompt_key: "prompt"  # Prompt field
      answer1_key: "answer1"  # First answer option
      answer2_key: "answer2"  # Second answer option
      chosen_key: "chosen"  # Chosen field
      rejected_key: "rejected"  # Rejected field

      # Enable notifications for this operator with detailed configuration
      notification_config:
        enabled: true  # Enable notifications

        # Email notification configuration
        email:
          enabled: true  # Email channel is enabled

          # SMTP server settings
          smtp_server: "smtp.alibaba-inc.com"
          smtp_port: 465

          # Sender information
          username: "your_user_name"
          # uncomment and put in your password
          # password: "your_password"
          sender_email: "your_email@alibaba-inc.com"
          sender_name: "your_name"

          # Recipients who will receive annotation status notifications
          recipients: ["email1@example.com", "email2@example.com"]

          # Subject prefix for notifications
          subject: "Annotation Status Update"

        # Configure which annotation events should trigger notifications
        notification_events:
          task_created: false      # Don't notify for each task creation
          batch_created: true      # Notify when a batch of tasks is created
          annotation_completed: false  # Notify when annotations complete
          batch_annotation_completed: true  # Notify when batch annotations complete
          error_occurred: true     # Notify on errors (always sent via email)
