# Filter ops
image_watermark_filter:
  desc: Filter to keep samples whose images have no watermark with high probability.
  args:
    hf_watermark_model:
      desc: watermark detection model name on huggingface.
      type: str
      default: amrul-hzz/watermark_detector
    trust_remote_code:
      desc: Whether to trust the remote code for loading huggingface model.
      type: bool
      default: false
    prob_threshold:
      desc: the predicted watermark probability threshold for samples. range from
        0 to 1. Samples with watermark probability less than this threshold will be
        kept.
      type: float
      default: 0.8
      min: 0.0
      max: 1.0
    any_or_all:
      desc: 'keep this sample with ''any'' or ''all'' strategy of all images. ''any'':
        keep this sample if any images meet the condition. ''all'': keep this sample
        only if all images meet the condition.'
      type: str
      default: any
      options:
          - any
          - all
#llm_quality_score_filter:
#    args:
#        api_or_hf_model:
#
#        min_score: float = 0.5,
language_id_score_filter:
  desc: Filter to keep samples in a specific language with confidence score larger
    than a specific min value.
  args:
    lang:
      desc: Samples in which languages to keep.
      type: Union[str, List[str]]
      default: ''
    min_score:
      desc: The min language identification confidence scores of samples to keep.
      type: float
      default: 0.8
      min: -1000000.0
      max: 1000000.0

alphanumeric_filter:
  desc: Filter to keep samples with alphabet/numeric ratio within a specific range.
  args:
    tokenization:
      desc: Whether to count the ratio of alphanumeric to the total number of tokens.
        if tokenization=False, it will count the ratio of alphanumeric to the total
        number of characters.
      type: bool
      default: false
    min_ratio:
      desc: The min filter ratio in alphanumeric op, samples will be filtered if their
        alphabet/numeric ratio is below this parameter.
      type: float
      default: 0.25
      min: -1000000.0
      max: 1000000.0
    max_ratio:
      desc: The max filter ratio in alphanumeric op, samples will be filtered if their
        alphabet/numeric ratio exceeds this parameter.
      type: float
      default: 1000000.0
      min: -1000000.0
      max: 1000000.0

#character_repetition_filter:                            # filter text with the character repetition ratio out of specific range
#    rep_len: 10                                             # repetition length for char-level n-gram
#    min_ratio: 0.0                                          # the min ratio of filter range
#    max_ratio: 0.5                                          # the max ratio of filter range
#flagged_words_filter:                                   # filter text with the flagged-word ratio larger than a specific max value
#    lang: en                                                # consider flagged words in what language
#    tokenization: false                                     # whether to use model to tokenize documents
#    max_ratio: 0.0045                                       # the max ratio to filter text
#    flagged_words_dir: ./assets                             # directory to store flagged words dictionaries
#    use_words_aug: false                                    # whether to augment words, especially for Chinese and Vietnamese
#    words_aug_group_sizes: [2]                              # the group size of words to augment
#    words_aug_join_char: ""                                 # the join char between words to augment
#maximum_line_length_filter:                             # filter text with the maximum length of lines out of specific range
#    min_len: 10                                             # the min length of filter range
#    max_len: 10000                                          # the max length of filter range
#perplexity_filter:                                      # filter text with perplexity score out of specific range
#    lang: en                                                # compute perplexity in what language
#    max_ppl: 1500                                           # the max perplexity score to filter text
#special_characters_filter:                              # filter text with special-char ratio out of specific range
#    min_ratio: 0.0                                          # the min ratio of filter range
#    max_ratio: 0.25                                         # the max ratio of filter range
#stopwords_filter:                                       # filter text with stopword ratio smaller than a specific min value
#    lang: en                                                # consider stopwords in what language
#    tokenization: false                                     # whether to use model to tokenize documents
#    min_ratio: 0.3                                          # the min ratio to filter text
#    stopwords_dir: ./assets                                 # directory to store stopwords dictionaries
#    use_words_aug: false                                    # whether to augment words, especially for Chinese and Vietnamese
#    words_aug_group_sizes: [2]                              # the group size of words to augment
#    words_aug_join_char: ""                                 # the join char between words to augment
#text_length_filter:                                     # filter text with length out of specific range
#    min_len: 10                                             # the min length of filter range
#    max_len: 10000                                          # the max length of filter range
#words_num_filter:                                       # filter text with number of words out of specific range
#    lang: en                                                # sample in which language
#    tokenization: false                                     # whether to use model to tokenize documents
#    min_num: 10                                             # the min number of filter range
#    max_num: 10000                                          # the max number of filter range
#word_repetition_filter:                                 # filter text with the word repetition ratio out of specific range
#    lang: en                                                # sample in which language
#    tokenization: false                                     # whether to use model to tokenize documents
#    rep_len: 10                                             # repetition length for word-level n-gram
#    min_ratio: 0.0                                          # the min ratio of filter range
#    max_ratio: 0.5                                          # the max ratio of filter range
