# docs/sphinx_doc/knowledge_base_conf.py

import os
import sys

path_to_dj_repo = os.getenv('PATH_TO_DJ_REPO', '../../../../../../data-juicer')
print(path_to_dj_repo)
sys.path.insert(0, os.path.abspath(path_to_dj_repo))

project = 'DataJuicer Knowledge Base'
copyright = 'test'
author = 'test'

extensions = [
    'sphinx.ext.autodoc',
    'sphinxcontrib.apidoc',
]

# apidoc settings
apidoc_module_dir = os.path.join(path_to_dj_repo, "data_juicer")
apidoc_output_dir = "./api"

# Prefix document path to section labels, otherwise autogenerated labels would
# look like 'heading' rather than 'path/to/file:heading'
autosectionlabel_prefix_document = True
autosummary_generate = True
autosummary_ignore_module_all = False
autodoc_member_order = "bysource"


html_theme = 'alabaster'

