"""
Copied from https://github.com/modelscope/agentscope/blob/main/applications/multisource_rag_app/src/asset/knowledge/conf.py

Data-Juicer adopts Apache 2.0 license, the original license of this file
is as follows:

Copyright 2024 Alibaba

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
# docs/sphinx_doc/knowledge_base_conf.py

import os
import sys

path_to_dj_repo = os.getenv('PATH_TO_DJ_REPO', '../../../../../../data-juicer')
print(path_to_dj_repo)
sys.path.insert(0, os.path.abspath(path_to_dj_repo))

project = 'DataJuicer Knowledge Base'
copyright = 'test'
author = 'test'

extensions = [
    'sphinx.ext.autodoc',
    'sphinxcontrib.apidoc',
]

# apidoc settings
apidoc_module_dir = os.path.join(path_to_dj_repo, "data_juicer")
apidoc_output_dir = "./api"

# Prefix document path to section labels, otherwise autogenerated labels would
# look like 'heading' rather than 'path/to/file:heading'
autosectionlabel_prefix_document = True
autosummary_generate = True
autosummary_ignore_module_all = False
autodoc_member_order = "bysource"


html_theme = 'alabaster'

