project_name: 'min'

np: 4  # number of subprocess to process your dataset
export_path: './outputs/'

text_keys: 'text'
video_key: 'videos'
image_key: 'images'
audio_key: 'audios'
executor_type: default                                      # type of executor, support "default" or "ray" for now.
ray_address: auto                                           # the address of the Ray cluster.
suffixes: null
add_suffix: false
