# global parameters
project_name: 'dataset-remote-modelscope'
dataset:
  configs:
    - type: 'remote'
      source: 'modelscope'
      path: 'modelscope/clue'
      subset_name: 'afqmc'
      split: 'train'
      limit: 1000
