# global parameters
project_name: 'dataset-remote-commoncrawl'
dataset:
  type: 'remote'
  subtype: 'commoncrawl'
  start_snapshot: '2020-50'
  end_snapshot: '2021-04'
  aws: true
  force_download: false
  url_limit: 2
