# global parameters
project_name: 'dataset-remote-wiki'
dataset:
  configs:
    - type: 'remote'
      source: 'wiki'
      lang: 'en'
      dump_date: 'latest'
      force_download: false
      url_limit: 2
