dataset:
  configs:
    - type: local
      path: /path/to/data.json

validators:
  - type: required_fields
    required_fields:
      - "text"
      - "metadata"
      - "language"
    field_types:
      text: "str"
      metadata: "dict"
      language: "str"
