project_name: validation_swift_messages_demo

dataset:
  configs:
    - type: local
      path: ./demos/data/demo-dataset-chatml.jsonl

text_keys: messages

export_path: ./outputs/validation_swift_messages_demo/output.jsonl

validators:
  - type: swift_messages
    min_turns: 1  # Minimum number of user-assistant turns
    max_turns: 20  # Maximum number of turns including system message

process:
  - text_length_filter:
      max_len: 18221 # 3sigma
