# Sandbox config example

# global parameters
project_name: 'medeval-sandbox'
experiment_name: 'medeval-sandbox-1'              # for wandb tracer name
work_dir: 'medeval/res/sub'                   # the default output dir for meta logging
hpo_config: null                                  # path to a configuration file when using auto-HPO tool.

probe_job_configs:

refine_recipe_job_configs:

evaluation_job_configs:
  - hook: 'EvaluateModelHook'
    meta_name: 'eval_model'
    extra_configs: 'configs/data_juicer_recipes/sandbox/medeval/medeval_yaml/all_in_one.yaml'
