# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: unittest-partial

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  unittest-single:
    runs-on: [GPU, unittest]
    environment: Testing
    steps:
    - uses: actions/checkout@v3
      with:
        path: dj-${{ github.run_id }}
        fetch-depth: 0

    - name: Setup docker compose
      working-directory: dj-${{ github.run_id }}/.github/workflows/docker
      run: |
        docker compose up -d

    - name: Install data-juicer
      working-directory: dj-${{ github.run_id }}/.github/workflows/docker
      run: |
        docker compose exec ray-head pip install -e .\[all\]
        docker compose exec ray-worker pip install -e .\[all\]

    - name: Clean dataset cache
      working-directory: dj-${{ github.run_id }}/.github/workflows/docker
      run: |
        docker compose exec ray-head rm -rf /data/huggingface/dataset

    - name: Run unittest standalone
      working-directory: dj-${{ github.run_id }}/.github/workflows/docker
      run: |
        docker compose exec -e OPENAI_BASE_URL=${{ secrets.OPENAI_BASE_URL }} -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} ray-head python tests/run.py --tag standalone --mode partial

    - name: Upload coverage report of standalone
      uses: actions/upload-artifact@v4
      with:
        name: coverage_report_standalone
        include-hidden-files: true
        path: dj-${{ github.run_id }}/coverage_report_standalone

    - name: Run unittest ray
      working-directory: dj-${{ github.run_id }}/.github/workflows/docker
      run: |
        docker compose exec ray-head python tests/run.py --tag ray --mode regression

    - name: Upload coverage report of ray
      uses: actions/upload-artifact@v4
      with:
        name: coverage_report_ray
        include-hidden-files: true
        path: dj-${{ github.run_id }}/coverage_report_ray

    - name: Remove docker compose
      working-directory: dj-${{ github.run_id }}/.github/workflows/docker
      if: always()
      run: |
        docker compose down --remove-orphans

    - name: Cleanup workspace
      if: always()
      run: |
        rm -rf  dj-${{ github.run_id }}
