# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: unittest-partial

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  unittest-single:
    runs-on: [GPU, unittest]
    environment: Testing
    steps:
    - uses: actions/checkout@v3
      with:
        path: dj-${{ github.run_id }}
        fetch-depth: 0

    - name: Setup docker compose
      working-directory: dj-${{ github.run_id }}/.github/workflows/docker
      run: |
        docker compose up -d

    - name: Install data-juicer
      working-directory: dj-${{ github.run_id }}/.github/workflows/docker
      run: |
        docker compose exec ray-head bash -c '/root/.local/bin/uv pip install --system -e .\[all\]'

    - name: Print Pip Dependency Tree
      working-directory: dj-${{ github.run_id }}/.github/workflows/docker
      run: |
        docker compose exec ray-head bash -c '/root/.local/bin/uv pip install --system pipdeptree'
        docker compose exec ray-head bash -c 'pipdeptree'

    - name: Clean dataset cache
      working-directory: dj-${{ github.run_id }}/.github/workflows/docker
      run: |
        docker compose exec ray-head rm -rf /data/huggingface/dataset

    - name: Run unittest standalone
      working-directory: dj-${{ github.run_id }}/.github/workflows/docker
      run: |
        docker compose exec -e OPENAI_BASE_URL=${{ secrets.OPENAI_BASE_URL }} -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} ray-head bash -c 'python tests/run.py --tag standalone --mode partial'
        docker compose exec ray-head bash -c 'coverage combine'

    - name: Upload coverage report of standalone
      uses: actions/upload-artifact@v4
      with:
        name: coverage_report_standalone
        include-hidden-files: true
        path: dj-${{ github.run_id }}/.coverage

    - name: Remove docker compose
      working-directory: dj-${{ github.run_id }}/.github/workflows/docker
      if: always()
      run: |
        docker compose down --remove-orphans

    - name: Cleanup workspace
      if: always()
      run: |
        rm -rf  dj-${{ github.run_id }}

  unittest-dist:
    runs-on: [GPU, unittest]
    environment: Testing
    steps:
    - uses: actions/checkout@v3
      with:
        path: dj-${{ github.run_id }}
        fetch-depth: 0

    - name: Setup docker compose
      working-directory: dj-${{ github.run_id }}/.github/workflows/docker
      run: |
        docker compose up -d

    - name: Install data-juicer
      working-directory: dj-${{ github.run_id }}/.github/workflows/docker
      run: |
        docker compose exec ray-head bash -c '/root/.local/bin/uv pip install --system -e .\[all\]'
        docker compose exec ray-worker bash -c '/root/.local/bin/uv pip install --system -e .\[all\]'

    - name: Clean dataset cache
      working-directory: dj-${{ github.run_id }}/.github/workflows/docker
      run: |
        docker compose exec ray-head rm -rf /data/huggingface/dataset

    - name: Run unittest ray
      working-directory: dj-${{ github.run_id }}/.github/workflows/docker
      run: |
        docker compose exec ray-head bash -c 'python tests/run.py --tag ray --mode partial'
        docker compose exec ray-head bash -c 'coverage combine'

    - name: Upload coverage report of ray
      uses: actions/upload-artifact@v4
      with:
        name: coverage_report_ray
        include-hidden-files: true
        path: dj-${{ github.run_id }}/.coverage

    - name: Remove docker compose
      working-directory: dj-${{ github.run_id }}/.github/workflows/docker
      if: always()
      run: |
        docker compose down --remove-orphans

    - name: Cleanup workspace
      if: always()
      run: |
        rm -rf  dj-${{ github.run_id }}
